[phases.setup]
nixpkgs = ["php83", "php83Extensions.pdo_mysql", "composer", "nodejs_20", "npm"]

[phases.install]
cmds = [
  "composer install --no-interaction --prefer-dist",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
